name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.14' ]

    steps:
      - uses: actions/checkout@v2


      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build > BuildResults-${{ matrix.go-version }}


      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-TestResults-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
          name: Go-BuildResults-${{ matrix.go-version }}
          path: BuildResults-${{ matrix.go-version }}
